### ISSUE TITLE
tagsoup doesn't allow uppercase X in hexadecimal numerical character references

### ISSUE THREAD

**Issue by jgm** [ndmitchell/tagsoup#32]
See https://github.com/ndmitchell/tagsoup/blob/master/Text/HTML/TagSoup/Entity.hs#L36

And look at http://www.w3.org/TR/html5/syntax.html sec 8.1.4:

"Hexadecimal numeric character reference
The ampersand must be followed by a "#" (U+0023) character, which must be followed by either a "x" (U+0078) character or a "X" (U+0058) character, which ..."

**Comment by ndmitchell** [comment]
Thanks for the report. I'll sort this out this evening.

**Comment by ndmitchell** [comment]
So it turns out `parseTags` worked just fine with `&#X` because it doesn't actually use `lookupEntity` when it's a hex one, but instead does something more direct (because it follows the HTML5 spec and so has already consumed the right pieces). Still, worth fixing in `lookupEntity` as well, and test case added. All released as tagoup-0.13.7.

**Comment by jgm** [comment]
Thanks!

+++ Neil Mitchell [Jan 09 16 13:25 ]:
